server:
  port: 8087

spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false

app:
  kafka:
    topics:
      payment-events: payment-events
      user-events: user-events

logging:
  level:
    iuh.fit.se.notificationservice: INFO
    org.springframework.kafka: INFO
