services:
  db:
    image: mysql:5.7
    container_name: wp_mysql_bai1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123456
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_pass123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - wp_network

  wordpress:
    image: wordpress:latest
    container_name: wordpress_bai1
    restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_pass123
    ports:
      - "80:80"
    networks:
      - wp_network

volumes:
  db_data:

networks:
  wp_network:
    driver: bridge
