server:
  port: 8084

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mariadb://localhost:3306/movie_ticket_payment
    username: root
    password: khoa5604
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    admin:
      auto-create: true
    consumer:
      group-id: payment-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    listener:
      missing-topics-fatal: false

app:
  kafka:
    topics:
      booking-events: booking-events
      payment-events: payment-events
  payment:
    success-rate: 0

logging:
  level:
    iuh.fit.se.paymentservice: INFO
    org.springframework.kafka: INFO
